-- ----------------------------------------
-- Timezone Data

INSERT INTO `timezone` (`id`, `name`, `country`, `utc`, `dst`, `code`) VALUES
(1, 'Asia/Kabul', 'Afghanistan', '+0430', 'N', 'AFT'),
(2, 'Europe/Tirane', 'Albania', '+0100', 'Y', 'CET/CEST'),
(3, 'Africa/Algiers', 'Algeria', '+0100', 'N', 'CET'),
(4, 'Pacific/Samoa', 'American Samoa', '+1100', 'N', 'NFT'),
(5, 'Europe/Andorra', 'Andorra', '+0100', 'Y', 'CET/CEST'),
(6, 'Africa/Luanda', 'Angola', '+0100', 'N', 'WAT'),
(7, 'America/Anguilla', 'Anguilla (British)', '+0400', 'N', 'ANT'),
(8, 'Antarctica/Casey', 'Antarctica', '+1100', 'Y', 'ACT'),
(9, 'Antarctica/Davis', 'Antarctica', '+0500', 'Y', 'ACT'),
(10, 'Antarctica/DumontDUrville', 'Antarctica', '+1000', 'N', 'ACT'),
(11, 'Antarctica/Macquarie', 'Antarctica', '+1100', 'N', 'ACT'),
(12, 'Antarctica/Mawson', 'Antarctica', '+0500', 'N', 'ACT'),
(13, 'Antarctica/McMurdo', 'Antarctica', '+1200', 'Y', 'ACT'),
(14, 'Antarctica/Palmer', 'Antarctica', '-0400', 'Y', 'ACT'),
(15, 'Antarctica/Rothera', 'Antarctica', '-0300', 'N', 'ACT'),
(16, 'Antarctica/South_Pole', 'Antarctica', '+1200', 'Y', 'ACT'),
(17, 'Antarctica/Syowa', 'Antarctica', '+0300', 'N', 'ACT'),
(18, 'Antarctica/Vostok', 'Antarctica', '+0600', 'N', 'ACT'),
(19, 'America/Halifax', 'Antigua and Barbuda', '-0400', 'N', 'AST'),
(20, 'America/Argentina/Buenos_Aires', 'Argentine', '-0300', 'N', 'ART'),
(21, 'America/Argentina/Catamarca', 'Argentine', '-0300', 'N', 'ART'),
(22, 'America/Argentina/ComodRivadabvia', 'Argentine', '-0300', 'N', 'ART'),
(23, 'America/Argentina/Cordoba', 'Argentine', '-0300', 'N', 'ART'),
(24, 'America/Argentina/Jujuy', 'Argentine', '-0300', 'N', 'ART'),
(25, 'America/Argentina/La_Rioja', 'Argentine', '-0300', 'N', 'ART'),
(26, 'America/Argentina/Mendoza', 'Argentine', '-0300', 'N', 'ART'),
(27, 'America/Argentina/Rio_Gallegos', 'Argentine', '-0300', 'N', 'ART'),
(28, 'America/Argentina/Salta', 'Argentine', '-0300', 'N', 'ART'),
(29, 'America/Argentina/San_Juan', 'Argentine', '-0300', 'N', 'ART'),
(30, 'America/Argentina/San_Luis', 'Argentine', '-0300', 'N', 'ART'),
(31, 'America/Argentina/Tucuman', 'Argentine', '-0300', 'N', 'ART'),
(32, 'America/Argentina/Ushuaia', 'Argentine', '-0300', 'N', 'ART'),
(33, 'Asia/Yerevan', 'Armenia', '+0400', 'Y', 'AMT/AMST'),
(34, 'America/Aruba', 'Aruba', '-0400', 'N', 'AST'),
(35, 'Australia/Adelaide', 'Australia', '+0930', 'Y', 'ACST'),
(36, 'Australia/Brisbane', 'Australia', '+1000', 'N', 'AEST'),
(37, 'Australia/Broken_Hill', 'Australia', '+0930', 'Y', 'ACST'),
(38, 'Australia/Currie', 'Australia', '+1000', 'Y', 'AEST'),
(39, 'Australia/Darwin', 'Australia', '+0930', 'N', 'ACST'),
(40, 'Australia/Eucla', 'Australia', '+0845', 'Y', 'CWST'),
(41, 'Australia/Hobart', 'Australia', '+1000', 'Y', 'AEST'),
(42, 'Australia/Lindeman', 'Australia', '+1000', 'N', 'AEST'),
(43, 'Australia/Lord_Howe', 'Australia', '+1030', 'Y', 'LHST'),
(44, 'Australia/Melbourne', 'Australia', '+1000', 'Y', 'AEST'),
(45, 'Australia/Perth', 'Australia', '+0800', 'Y', 'AWST'),
(46, 'Australia/Sydney', 'Australia', '+1000', 'Y', 'AEST'),
(47, 'Pacific/Norfolk', 'Australia', '+1130', 'N', 'NFT'),
(48, 'Europe/Vienna', 'Austria', '+0100', 'Y', 'CET/CEST'),
(49, 'Asia/Baku', 'Azerbaijan', '+0400', 'Y', 'AZT/AZST'),
(50, 'America/Nassau', 'Bahamas', '-0500', 'Y', 'EST/EDT'),
(51, 'Asia/Bahrain', 'Bahrain', '+0300', 'N', 'AST'),
(52, 'Asia/Dhaka', 'Bangladesh', '+0600', 'N', 'BDST'),
(53, 'America/Barbados', 'Barbados', '-0400', 'N', 'AST'),
(54, 'Europe/Minsk', 'Belarus', '+0200', 'Y', 'EET/EEST'),
(55, 'Europe/Brussels', 'Belgium', '+0100', 'Y', 'CET/CEST'),
(56, 'America/Belize', 'Belize', '-0600', 'N', 'CST'),
(57, 'Africa/Porto-Novo', 'Benin', '+0100', 'N', 'WAT'),
(58, 'Atlantic/Bermuda', 'Bermuda', '-0400', 'Y', 'AST/ADT'),
(59, 'Asia/Thimphu', 'Bhutan', '+0600', 'N', 'BTT'),
(60, 'America/La_Paz', 'Bolivia', '-0400', 'N', 'BOT'),
(61, 'Europe/Sarajevo', 'Bosnia and Herzegovina', '+0100', 'Y', 'CET/CEST'),
(62, 'Africa/Gaborone', 'Botswana', '+0200', 'N', 'CAT'),
(63, 'America/Araguaina', 'Brazil', '-0300', 'N', 'BRT'),
(64, 'America/Bahia', 'Brazil', '-0300', 'N', 'BRT'),
(65, 'America/Belem', 'Brazil', '-0300', 'N', 'BRT'),
(66, 'America/Boa_Vista', 'Brazil', '-0400', 'N', 'AMT'),
(67, 'America/Campo_Grande', 'Brazil', '-0400', 'Y', 'AMT/AMST'),
(68, 'America/Cuiaba', 'Brazil', '-0400', 'Y', 'AMT/AMST'),
(69, 'America/Eirunepe', 'Brazil', '-0400', 'N', 'AMT'),
(70, 'America/Fortaleza', 'Brazil', '-0300', 'N', 'BRT'),
(71, 'America/Maceio', 'Brazil', '-0300', 'N', 'BRT'),
(72, 'America/Manaus', 'Brazil', '-0400', 'N', 'AMT'),
(73, 'America/Noronha', 'Brazil', '-0200', 'N', 'FNT'),
(74, 'America/Porto_Velho', 'Brazil', '-0400', 'N', 'AMT'),
(75, 'America/Recife', 'Brazil', '-0300', 'N', 'BRT'),
(76, 'America/Rio_Branco', 'Brazil', '-0400', 'N', 'AMT'),
(77, 'America/Santarem', 'Brazil', '-0400', 'N', 'AMT'),
(78, 'America/Sao_Paulo', 'Brazil', '-0300', 'Y', 'BRT/BRST'),
(79, 'America/Tortola', 'British Virgin Islands', '-0400', 'N', 'AST'),
(80, 'Asia/Brunei', 'Brunei Darussalam', '+0800', 'N', 'BNT'),
(81, 'Europe/Sofia', 'Bulgaria', '+0200', 'Y', 'EET/EEST'),
(82, 'Africa/Ouagadougou', 'Burkina Faso', '+0000', 'N', 'GMT'),
(83, 'Africa/Bujumbura', 'Burundi', '+0200', 'N', 'CAT'),
(84, 'Asia/Phnom_Penh', 'Cambodia', '+0700', 'N', 'ICT'),
(85, 'Africa/Douala', 'Cameroon', '+0100', 'N', 'WAT'),
(86, 'America/Atikokan', 'Canada', '-0500', 'N', 'EST'),
(87, 'America/Blanc-Sablon', 'Canada', '-0400', 'N', 'AST'),
(88, 'America/Cambridge_Bay', 'Canada', '-0700', 'Y', 'MST/MDT'),
(89, 'America/Coral_Harbour', 'Canada', '-0500', 'N', 'EST'),
(90, 'America/Dawson', 'Canada', '-0800', 'Y', 'PST/PDT'),
(91, 'America/Dawson_Creek', 'Canada', '-0700', 'N', 'MST'),
(92, 'America/Edmonton', 'Canada', '-0700', 'Y', 'MST/MDT'),
(93, 'America/Glace_Bay', 'Canada', '-0400', 'Y', 'AST/ADT'),
(94, 'America/Goose_Bay', 'Canada', '-0400', 'Y', 'AST/ADT'),
(95, 'America/Inuvik', 'Canada', '-0700', 'Y', 'MST/MDT'),
(96, 'America/Iqaluit', 'Canada', '-0500', 'Y', 'EST/EDT'),
(97, 'America/Moncton', 'Canada', '-0400', 'Y', 'AST/ADT'),
(98, 'America/Montreal', 'Canada', '-0500', 'Y', 'EST/EDT'),
(99, 'America/Nipigon', 'Canada', '-0500', 'Y', 'EST/EDT'),
(100, 'America/Pangnirtung', 'Canada', '-0500', 'Y', 'EST/EDT'),
(101, 'America/Rainy_River', 'Canada', '-0600', 'Y', 'CST/CDT'),
(102, 'America/Rankin_Inlet', 'Canada', '-0600', 'Y', 'CST/CDT'),
(103, 'America/Regina', 'Canada', '-0600', 'N', 'CST'),
(104, 'America/Resolute', 'Canada', '-0500', 'Y', 'EST/EDT'),
(105, 'America/St_Johns', 'Canada', '-0330', 'Y', 'NST/NDT'),
(106, 'America/Swift_Current', 'Canada', '-0600', 'N', 'CST'),
(107, 'America/Thunder_Bay', 'Canada', '-0500', 'Y', 'EST/EDT'),
(108, 'America/Toronto', 'Canada', '-0500', 'Y', 'EST/EDT'),
(109, 'America/Vancouver', 'Canada', '-0800', 'Y', 'PST/PDT'),
(110, 'America/Whitehorse', 'Canada', '-0800', 'Y', 'PST/PDT'),
(111, 'America/Winnipeg', 'Canada', '-0600', 'Y', 'CST/CDT'),
(112, 'America/Yellowknife', 'Canada', '-0700', 'Y', 'MST/MDT'),
(113, 'America/Creston', 'Canada', '-0700', 'N', 'CT'),
(114, 'Atlantic/Cape_Verde', 'Cape Verde', '-0100', 'N', 'CVT'),
(115, 'America/Cayman', 'Cayman Islands', '-0500', 'N', 'EST'),
(116, 'Africa/Bangui', 'Central African Republic', '+0100', 'N', 'WAT'),
(117, 'Africa/Ndjamena', 'Chad', '+0100', 'N', 'WAT'),
(118, 'America/Santiago', 'Chile', '-0400', 'Y', 'CLT/CLST'),
(119, 'Pacific/Easter', 'Chile', '-0600', 'Y', 'EAST/EASST'),
(120, 'Asia/Shanghai', 'China', '+0800', 'N', 'CST'),
(121, 'Asia/Chongqing', 'China', '+0800', 'N', 'CNT'),
(122, 'Asia/Harbin', 'China', '+0800', 'N', 'CHT'),
(123, 'America/Bogota', 'Colombia', '-0500', 'N', 'COT'),
(124, 'Indian/Comoro', 'Comoros', '+0300', 'N', 'EAT'),
(125, 'Africa/Brazzaville', 'Congo (Brazzville)', '+0100', 'N', 'WAT'),
(126, 'Africa/Kinshasa', 'Congo DR', '+0100', 'N', 'WAT'),
(127, 'Africa/Lubumbashi', 'Congo DR', '+0200', 'N', 'CAT'),
(128, 'America/Costa_Rica', 'Costa Rica', '-0600', 'N', 'CST'),
(129, 'Europe/Zagreb', 'Croatia', '+0100', 'Y', 'CET/CEST'),
(130, 'America/Havana', 'Cuba', '-0500', 'Y', 'CST/CDT'),
(131, 'America/Curacao', 'Curacao', '-0400', 'N', 'CUT'),
(132, 'Asia/Nicosia', 'Cyprus', '+0200', 'Y', 'EET/EEST'),
(133, 'Europe/Prague', 'Czech Republic', '+0100', 'Y', 'CET/CEST'),
(134, 'Europe/Copenhagen', 'Denmark', '+0100', 'Y', 'CET/CEST'),
(135, 'Africa/Djibouti', 'Djibouti', '+0300', 'N', 'EAT'),
(136, 'America/Dominica', 'Dominica', '-0400', 'N', 'AST'),
(137, 'America/Santo_Domingo', 'Dominican Republic', '-0400', 'N', 'AST'),
(138, 'Asia/Dili', 'East Timor', '+0900', 'N', 'TLT'),
(139, 'America/Guayaquil', 'Ecuador', '-0500', 'N', 'ECT'),
(140, 'Pacific/Galapagos', 'Ecuador', '-0600', 'N', 'GALT'),
(141, 'Africa/Cairo', 'Egypt', '+0200', 'Y', 'EET/EEST'),
(142, 'America/El_Salvador', 'El Salvador', '-0600', 'N', 'CST'),
(143, 'Africa/Malabo', 'Equatorial Guinea', '+0100', 'N', 'WAT'),
(144, 'Africa/Asmara', 'Eritrea', '+0300', 'N', 'EAT'),
(145, 'Europe/Tallinn', 'Estonia', '+0200', 'Y', 'EET/EEST'),
(146, 'Africa/Addis_Ababa', 'Ethiopia', '+0300', 'N', 'EAT'),
(147, 'Atlantic/Faroe', 'Faroe Islands', '+0000', 'Y', 'WET/WEST'),
(148, 'Pacific/Fiji', 'Fiji', '+1200', 'N', 'FJT'),
(149, 'Europe/Helsinki', 'Finland', '+0200', 'Y', 'EET/EEST'),
(150, 'Europe/Paris', 'France', '+0100', 'Y', 'CET/CEST'),
(151, 'America/Cayenne', 'French Guiana', '-0300', 'N', 'GFT'),
(152, 'Pacific/Gambier', 'French Polynesia', '-0900', 'N', 'GAMT'),
(153, 'Pacific/Marquesas', 'French Polynesia', '-0930', 'N', 'MART'),
(154, 'Pacific/Tahiti', 'French Polynesia', '-1000', 'N', 'TAHT'),
(155, 'Africa/Libreville', 'Gabon', '+0100', 'N', 'WAT'),
(156, 'Africa/Banjul', 'Gambia', '+0000', 'N', 'GMT'),
(157, 'Asia/Tbilisi', 'Georgia', '+0400', 'N', 'GET'),
(158, 'Europe/Berlin', 'Germany', '+0100', 'Y', 'CET/CEST'),
(159, 'Africa/Accra', 'Ghana', '+0000', 'N', 'GMT'),
(160, 'Europe/Gibraltar', 'Gibraltar', '+0100', 'Y', 'CET/CEST'),
(161, 'Europe/Athens', 'Greece', '+0200', 'Y', 'EET/EEST'),
(162, 'America/Danmarkshavn', 'Greenland', '+0000', 'N', 'GMT'),
(163, 'America/Godthab', 'Greenland', '-0300', 'Y', 'WGT/WGST'),
(164, 'America/Scoresbysund', 'Greenland', '-0100', 'Y', 'EGT/EGST'),
(165, 'America/Thule', 'Greenland', '-0400', 'Y', 'AST/ADT'),
(166, 'America/Grenada', 'Grenada', '-0400', 'N', 'AST'),
(167, 'America/Guadeloupe', 'Guadeloupe', '-0400', 'N', 'AST'),
(168, 'Pacific/Guam', 'Guam', '+1000', 'N', 'AEST'),
(169, 'America/Guatemala', 'Guatemala', '-0600', 'N', 'CST'),
(170, 'Europe/Guernsey', 'Guernsey', '+0000', 'Y', 'GMT/BST'),
(171, 'Africa/Conakry', 'Guinea', '+0000', 'N', 'GMT'),
(172, 'Africa/Bissau', 'Guinea-Bissau', '+0000', 'N', 'GMT'),
(173, 'America/Guyana', 'Guyana', '-0400', 'N', 'GYT'),
(174, 'America/Port-au-Prince', 'Haiti', '-0500', 'N', 'EST'),
(175, 'America/Tegucigalpa', 'Honduras', '-0600', 'N', 'CST'),
(176, 'Asia/Hong_Kong', 'Hong Kong', '+0800', 'N', 'HKT'),
(177, 'Europe/Budapest', 'Hungary', '+0100', 'Y', 'CET/CEST'),
(178, 'Atlantic/Reykjavik', 'Iceland', '+0000', 'N', 'GMT'),
(179, 'Asia/Kolkata', 'India', '+0530', 'N', 'IST'),
(180, 'Asia/Jakarta', 'Indonesia', '+0700', 'N', 'WIT'),
(181, 'Asia/Jayapura', 'Indonesia', '+0900', 'N', 'EIT'),
(182, 'Asia/Makassar', 'Indonesia', '+0800', 'N', 'CIT'),
(183, 'Asia/Tehran', 'Iran', '+0330', 'N', 'IRST'),
(184, 'Asia/Baghdad', 'Iraq', '+0300', 'Y', 'AST/ADT'),
(185, 'Europe/Dublin', 'Ireland', '+0000', 'Y', 'GMT/IST'),
(186, 'Europe/Isle_of_Man', 'Isle of Man', '+0000', 'Y', 'GMT/BST'),
(187, 'Asia/Jerusalem', 'Israel', '+0200', 'Y', 'IST/IDT'),
(188, 'Europe/Rome', 'Italy', '+0100', 'Y', 'CET/CEST'),
(189, 'Africa/Abidjan', 'Ivory Coast', '+0000', 'N', 'GMT'),
(190, 'America/Jamaica', 'Jamaica', '-0500', 'N', 'EST'),
(191, 'Asia/Tokyo', 'Japan', '+0900', 'N', 'JST'),
(192, 'Europe/Jersey', 'Jersey', '+0000', 'Y', 'GMT/BST'),
(193, 'Asia/Amman', 'Jordan', '+0200', 'Y', 'EET/EEST'),
(194, 'Asia/Almaty', 'Kazakhstan', '+0600', 'N', 'ALMT'),
(195, 'Asia/Aqtau', 'Kazakhstan', '+0500', 'N', 'AQTT'),
(196, 'Asia/Aqtobe', 'Kazakhstan', '+0500', 'N', 'AQTT'),
(197, 'Asia/Oral', 'Kazakhstan', '+0500', 'N', 'ORAT'),
(198, 'Asia/Qyzylorda', 'Kazakhstan', '+0600', 'N', 'QYZT'),
(199, 'Africa/Nairobi', 'Kenya', '+0300', 'N', 'EAT'),
(200, 'Pacific/Enderbury', 'Kiribati', '+1300', 'N', 'PHOT'),
(201, 'Pacific/Kiritimati', 'Kiribati', '+1400', 'N', 'LINT'),
(202, 'Pacific/Tarawa', 'Kiribati', '+1200', 'N', 'GILT'),
(203, 'Asia/Kuwait', 'Kuwait', '+0300', 'N', 'AST'),
(204, 'Asia/Bishkek', 'Kyrgyzstan', '+0600', 'N', 'KGT'),
(205, 'Asia/Vientiane', 'Laos', '+0700', 'N', 'ICT'),
(206, 'Europe/Riga', 'Latvia', '+0200', 'Y', 'EET/EEST'),
(207, 'Asia/Beirut', 'Lebanon', '+0200', 'Y', 'EET/EEST'),
(208, 'Africa/Maseru', 'Lesotho', '+0200', 'N', 'SAST'),
(209, 'Africa/Monrovia', 'Liberia', '+0000', 'N', 'GMT'),
(210, 'Africa/Tripoli', 'Libya', '+0200', 'N', 'EET'),
(211, 'Europe/Vaduz', 'Liechtenstein', '+0100', 'Y', 'CET/CEST'),
(212, 'Europe/Vilnius', 'Lithuania', '+0200', 'Y', 'EET/EEST'),
(213, 'Europe/Luxembourg', 'Luxembourg', '+0100', 'Y', 'CET/CEST'),
(214, 'Asia/Macau', 'Macau', '+0800', 'N', 'CT'),
(215, 'Europe/Skopje', 'Macedonia', '+0100', 'Y', 'CET/CEST'),
(216, 'Indian/Antananarivo', 'Madagascar', '+0300', 'N', 'EAT'),
(217, 'Africa/Blantyre', 'Malawi', '+0200', 'N', 'CAT'),
(218, 'Asia/Kuala_Lumpur', 'Malaysia', '+0800', 'N', 'MYT'),
(219, 'Indian/Maldives', 'Maldives', '+0500', 'N', 'MVT'),
(220, 'Africa/Bamako', 'Mali', '+0000', 'N', 'GMT'),
(221, 'Africa/Timbuktu', 'Mali', '+0000', 'N', 'GMT'),
(222, 'Europe/Malta', 'Malta', '+0100', 'Y', 'CET/CEST'),
(223, 'Pacific/Kwajalein', 'Marshall Islands', '+1200', 'N', 'MHT'),
(224, 'Pacific/Majuro', 'Marshall Islands', '+1200', 'N', 'MHT'),
(225, 'America/Martinique', 'Martinique', '-0400', 'N', 'AST'),
(226, 'Africa/Nouakchott', 'Mauritania', '+0000', 'N', 'GMT'),
(227, 'Indian/Mauritius', 'Mauritius', '+0400', 'N', 'MUT'),
(228, 'Indian/Mayotte', 'Mayotte', '+0300', 'N', 'EAT'),
(229, 'America/Cancun', 'Mexico', '-0600', 'Y', 'CST/CDT'),
(230, 'America/Chihuahua', 'Mexico', '-0700', 'Y', 'MST/MDT'),
(231, 'America/Hermosillo', 'Mexico', '-0700', 'N', 'MST'),
(232, 'America/Mazatlan', 'Mexico', '-0700', 'Y', 'MST/MDT'),
(233, 'America/Merida', 'Mexico', '-0600', 'Y', 'CST/CDT'),
(234, 'America/Mexico_City', 'Mexico', '-0600', 'Y', 'CST/CDT'),
(235, 'America/Monterrey', 'Mexico', '-0600', 'Y', 'CST/CDT'),
(236, 'America/Tijuana', 'Mexico', '-0800', 'Y', 'PST/PDT'),
(237, 'America/Ojinaga', 'Mexico', '-0700', 'Y', 'MST/MDT'),
(238, 'America/Santa_Isabel', 'Mexico', '-0800', 'Y', 'PST/PDT'),
(239, 'America/Bahia_Banderas', 'Mexico', '-0600', 'Y', 'CST/CDT'),
(240, 'America/Matamoros', 'Mexico', '-0600', 'Y', 'CST/CDT'),
(241, 'America/Ensenada', 'Mexico', '-0800', 'Y', 'BCT'),
(242, 'Pacific/Kosrae', 'Micronesia', '+1100', 'N', 'KOST'),
(243, 'Pacific/Ponape', 'Micronesia', '+1100', 'N', 'PONT'),
(244, 'Pacific/Truk', 'Micronesia', '+1000', 'N', 'TRUT'),
(245, 'Pacific/Yap', 'Micronesia', '+0300', 'N', 'YAPT'),
(246, 'Europe/Chisinau', 'Moldova', '+0200', 'Y', 'EET/EEST'),
(247, 'Europe/Monaco', 'Monaco', '+0100', 'Y', 'CET/CEST'),
(248, 'Asia/Choibalsan', 'Mongolia', '+0900', 'Y', 'CHOT/CHOST'),
(249, 'Asia/Hovd', 'Mongolia', '+0700', 'Y', 'HOVT/HOVST'),
(250, 'Asia/Ulaanbaatar', 'Mongolia', '+0800', 'Y', 'ULAT/ULAST'),
(251, 'Europe/Podgorica', 'Montenegro', '+0100', 'Y', 'CET/CEST'),
(252, 'America/Montserrat', 'Montserrat', '-0400', 'N', 'MST'),
(253, 'Africa/Casablanca', 'Morocco', '+0000', 'N', 'WET'),
(254, 'Africa/Maputo', 'Mozambique', '+0200', 'N', 'CAT'),
(255, 'Asia/Rangoon', 'Myanmar', '+0630', 'N', 'MMT'),
(256, 'Africa/Windhoek', 'Namibia', '+0100', 'Y', 'WAT/WAST'),
(257, 'Pacific/Nauru', 'Nauru', '+1200', 'N', 'NRT'),
(258, 'Asia/Katmandu', 'Nepal', '+0545', 'N', 'NPT'),
(259, 'Europe/Amsterdam', 'Netherlands', '+0100', 'Y', 'CET/CEST'),
(260, 'Pacific/Noumea', 'New Caledonia', '+1100', 'N', 'NCT'),
(261, 'Pacific/Auckland', 'New Zealand', '+1200', 'Y', 'NZST/NZDT'),
(262, 'Pacific/Chatham', 'New Zealand', '+1245', 'Y', 'CHAST/CHADT'),
(263, 'America/Managua', 'Nicaragua', '-0600', 'N', 'CST'),
(264, 'Africa/Niamey', 'Niger', '+0100', 'N', 'WAT'),
(265, 'Africa/Lagos', 'Nigeria', '+0100', 'N', 'WAT'),
(266, 'Asia/Seoul', 'North Korea', '+0900', 'N', 'KST'),
(267, 'Europe/Oslo', 'Norway', '+0100', 'Y', 'CET/CEST'),
(268, 'Asia/Muscat', 'Oman', '+0400', 'N', 'GST'),
(269, 'Asia/Karachi', 'Pakistan', '+0500', 'Y', 'PKT/PKST'),
(270, 'Pacific/Palau', 'Palau', '+0900', 'N', 'PWT'),
(272, 'Asia/Gaza', 'Palestine (Gaza)', '+0200', 'Y', 'GST'),
(273, 'Asia/Hebron', 'Palestine (Gaza)', '+0800', 'N', 'GST'),
(274, 'America/Panama', 'Panama', '-0500', 'N', 'EST'),
(275, 'Pacific/Port_Moresby', 'Papua New Guinea', '+1000', 'N', 'PGT'),
(276, 'America/Asuncion', 'Paraguay', '-0400', 'Y', 'PYT/PYST'),
(277, 'America/Lima', 'Peru', '-0500', 'N', 'PET'),
(278, 'Asia/Manila', 'Philippines', '+0800', 'N', 'PHT'),
(279, 'Europe/Warsaw', 'Poland', '+0100', 'Y', 'CET/CEST'),
(280, 'Atlantic/Azores', 'Portugal', '-0100', 'Y', 'AZOT/AZOST'),
(281, 'Atlantic/Madeira', 'Portugal', '-0100', 'Y', 'WET/WEST'),
(282, 'Europe/Lisbon', 'Portugal', '+0000', 'Y', 'WET/WEST'),
(283, 'America/Puerto_Rico', 'Puerto Rico', '-0400', 'N', 'AST'),
(284, 'Asia/Riyadh', 'Qatar', '+0300', 'N', 'AST'),
(285, 'Indian/Reunion', 'Réunion', '+0400', 'N', 'RET'),
(286, 'Europe/Bucharest', 'Romania', '+0200', 'Y', 'EET/EEST'),
(287, 'Asia/Anadyr', 'Russia', '+1200', 'Y', 'ANAT/ANAST'),
(288, 'Asia/Irkutsk', 'Russia', '+0800', 'Y', 'IRKT/IRKST'),
(289, 'Asia/Kamchatka', 'Russia', '+1200', 'Y', 'PETT/PETST'),
(290, 'Asia/Krasnoyarsk', 'Russia', '+0700', 'Y', 'KRAT/KRAST'),
(291, 'Asia/Magadan', 'Russia', '+1100', 'Y', 'MAGT/MAGST'),
(292, 'Asia/Novokuznetsk', 'Russia', '+0600', 'Y', 'NOVT/NOVST'),
(293, 'Asia/Novosibirsk', 'Russia', '+0600', 'Y', 'NOVT/NOVST'),
(294, 'Asia/Omsk', 'Russia', '+0600', 'Y', 'OMST/OMSST'),
(295, 'Asia/Sakhalin', 'Russia', '+1000', 'Y', 'SAKT/SAKST'),
(296, 'Asia/Vladivostok', 'Russia', '+1000', 'Y', 'VLAT/VLAST'),
(297, 'Asia/Yakutsk', 'Russia', '+0900', 'Y', 'YAKT/YAKST'),
(298, 'Asia/Yekaterinburg', 'Russia', '+0500', 'Y', 'YEKT/YEKST'),
(299, 'Europe/Kaliningrad', 'Russia', '+0200', 'Y', 'EET/EEST'),
(300, 'Europe/Moscow', 'Russia', '+0300', 'Y', 'MSK/MSD'),
(301, 'Europe/Samara', 'Russia', '+0400', 'Y', 'SAMT/SAMST'),
(302, 'Europe/Volgograd', 'Russia', '+0300', 'Y', 'VOLT/VOLST'),
(303, 'Africa/Kigali', 'Rwanda', '+0200', 'N', 'CAT'),
(304, 'Africa/El_Aaiun', 'Sahrawi Arab', '+0000', 'N', 'WST'),
(305, 'America/St_Barthelemy', 'Saint Barthelme', '-0400', 'N', 'AST'),
(306, 'America/St_Kitts', 'Saint Kitts and Nevis', '-0400', 'N', 'AST'),
(307, 'America/St_Lucia', 'Saint Lucia', '-0400', 'N', 'AST'),
(308, 'America/St_Martin', 'Saint Martin', '-0400', 'N', 'AST'),
(309, 'America/Marigot', 'Saint Martin', '-0400', 'N', 'MAT'),
(310, 'America/Miquelon', 'Saint Pierre And Miquelon', '-0300', 'Y', 'PMST/PMDT'),
(311, 'America/St_Vincent', 'Saint Vincent and the Grenadines', '-0400', 'N', 'AST'),
(312, 'Pacific/Apia', 'Samoa', '-1100', 'N', 'WST'),
(313, 'Europe/San_Marino', 'San Marino', '+0100', 'Y', 'CET/CEST'),
(314, 'Africa/Sao_Tome', 'São Tomé and Príncipe', '+0000', 'N', 'GMT'),
(316, 'Africa/Dakar', 'Senegal', '+0000', 'N', 'GMT'),
(317, 'Europe/Belgrade', 'Serbia', '+0100', 'Y', 'CET/CEST'),
(318, 'Indian/Mahe', 'Seychelles', '+0400', 'N', 'SCT'),
(319, 'Africa/Freetown', 'Sierra Leone', '+0000', 'N', 'GMT'),
(320, 'Asia/Singapore', 'Singapore', '+0800', 'N', 'SGT'),
(322, 'America/Lower_Princes', 'Sint Maarten', '+0400', 'N', 'SXT'),
(324, 'Europe/Ljubljana', 'Slovenia', '+0100', 'Y', 'CET/CEST'),
(325, 'Pacific/Guadalcanal', 'Solomon Islands', '+1100', 'N', 'SBT'),
(326, 'Africa/Mogadishu', 'Somalia', '+0300', 'N', 'EAT'),
(327, 'Africa/Johannesburg', 'South Africa', '+0200', 'N', 'SAST'),
(328, 'Asia/Pyongyang', 'South Korea', '+0900', 'N', 'KST'),
(329, 'Africa/Khartoum', 'South Sudan', '+0300', 'N', 'EAT'),
(330, 'Africa/Juba', 'South Sudan', '+0300', 'N', 'SST'),
(331, 'Africa/Ceuta', 'Spain', '+0100', 'Y', 'CET/CEST'),
(332, 'Atlantic/Canary', 'Spain', '+0000', 'Y', 'WET/WEST'),
(333, 'Europe/Madrid', 'Spain', '+0100', 'Y', 'CET/CEST'),
(334, 'Asia/Colombo', 'Sri Lanka', '+0530', 'N', 'LKT'),
(336, 'America/Paramaribo', 'Suriname', '-0300', 'N', 'SRT'),
(337, 'Arctic/Longyearbyen', 'Svalbard and Jan Mayen', '+0100', 'Y', 'ACT'),
(338, 'Africa/Mbabane', 'Swaziland', '+0200', 'N', 'SAST'),
(339, 'Europe/Stockholm', 'Sweden', '+0100', 'Y', 'CET/CEST'),
(340, 'Europe/Zurich', 'Switzerland', '+0100', 'Y', 'CET/CEST'),
(341, 'Asia/Damascus', 'Syria', '+0200', 'Y', 'EET/EEST'),
(342, 'Asia/Taipei', 'Taiwan', '+0800', 'N', 'CST'),
(343, 'Asia/Dushanbe', 'Tajikistan', '+0500', 'N', 'TJT'),
(344, 'Africa/Dar_es_Salaam', 'Tanzania', '+0300', 'N', 'EAT'),
(345, 'Asia/Bangkok', 'Thailand', '+0700', 'N', 'ICT'),
(346, 'Africa/Lome', 'Togo', '+0000', 'N', 'GMT'),
(347, 'Pacific/Tongatapu', 'Tonga', '+1300', 'N', 'TOT'),
(348, 'America/Port_of_Spain', 'Trinidad and Tobago', '-0400', 'N', 'AST'),
(349, 'Africa/Tunis', 'Tunisia', '+0100', 'Y', 'CET/CEST'),
(350, 'Europe/Istanbul', 'Turkey', '+0200', 'Y', 'EET/EEST'),
(351, 'Asia/Ashgabat', 'Turkmenistan', '+0500', 'N', 'TMT'),
(352, 'America/Grand_Turk', 'Turks and Caicos Islands', '-0500', 'Y', 'EST/EDT'),
(353, 'Pacific/Funafuti', 'Tuvalu', '+1200', 'N', 'TVT'),
(354, 'Africa/Kampala', 'Uganda', '+0300', 'N', 'EAT'),
(355, 'Europe/Kiev', 'Ukraine', '+0200', 'Y', 'EET/EEST'),
(356, 'Asia/Dubai', 'United Arab Emirates', '+0400', 'N', 'GST'),
(357, 'Europe/London', 'United Kingdom', '+0000', 'Y', 'GMT/BST'),
(358, 'America/Adak', 'United States', '-1000', 'Y', 'HAST/HADT'),
(359, 'America/Anchorage', 'United States', '-0900', 'Y', 'AKST/AKDT'),
(360, 'America/Chicago', 'United States', '-0600', 'Y', 'CST/CDT'),
(361, 'America/Denver', 'United States', '-0700', 'Y', 'MST/MDT'),
(362, 'America/Detroit', 'United States', '-0500', 'Y', 'EST/EDT'),
(363, 'America/Indiana/Indianapolis', 'United States', '-0500', 'Y', 'EST/EDT'),
(364, 'America/Indiana/Knox', 'United States', '-0600', 'Y', 'CST/CDT'),
(365, 'America/Indiana/Marengo', 'United States', '-0500', 'Y', 'EST/EDT'),
(366, 'America/Indiana/Petersburg', 'United States', '-0500', 'Y', 'EST/EDT'),
(367, 'America/Indiana/Tell_City', 'United States', '-0600', 'Y', 'CST/CDT'),
(368, 'America/Indiana/Vevay', 'United States', '-0500', 'Y', 'EST/EDT'),
(369, 'America/Indiana/Vincennes', 'United States', '-0500', 'Y', 'EST/EDT'),
(370, 'America/Indiana/Winamac', 'United States', '-0500', 'Y', 'EST/EDT'),
(371, 'America/Juneau', 'United States', '-0900', 'Y', 'AKST/AKDT'),
(372, 'America/Kentucky/Louisville', 'United States', '-0500', 'Y', 'EST/EDT'),
(373, 'America/Kentucky/Monticello', 'United States', '-0500', 'Y', 'EST/EDT'),
(374, 'America/Los_Angeles', 'United States', '-0800', 'Y', 'PST/PDT'),
(375, 'America/Menominee', 'United States', '-0600', 'Y', 'CST/CDT'),
(376, 'America/New_York', 'United States', '-0500', 'Y', 'EST/EDT'),
(377, 'America/Nome', 'United States', '-0900', 'Y', 'AKST/AKDT'),
(378, 'America/Phoenix', 'United States', '-0700', 'N', 'MST'),
(379, 'America/Yakutat', 'United States', '-0900', 'Y', 'AKST/AKDT'),
(380, 'Pacific/Honolulu', 'United States', '-1000', 'N', 'HAST'),
(381, 'America/Boise', 'United States', '-0700', 'Y', 'MST'),
(382, 'America/North_Dakota/Beulah', 'United States', '-0600', 'Y', 'NDT'),
(383, 'America/North_Dakota/Center', 'United States', '-0600', 'Y', 'NDCT'),
(384, 'America/North_Dakota/New_Salem', 'United States', '-0600', 'Y', 'NDNST'),
(385, 'America/Shiprock', 'United States', '-0700', 'Y', 'AST'),
(386, 'America/Sitka', 'United States', '-0900', 'Y', 'SKT'),
(387, 'America/Montevideo', 'Uruguay', '-0300', 'Y', 'UYT/UYST'),
(388, 'Asia/Samarkand', 'Uzbekistan', '+0500', 'N', 'UZT'),
(389, 'Pacific/Efate', 'Vanuatu', '+1100', 'N', 'VUT'),
(390, 'Europe/Vatican', 'Vatican City State (Holy See)', '+0100', 'Y', 'CET/CEST'),
(391, 'America/Caracas', 'Venezuela', '-0430', 'N', 'VET'),
(392, 'Asia/Ho_Chi_Minh', 'Viet Nam', '+0700', 'N', 'ICT'),
(393, 'Pacific/Wallis', 'Wallis and Futuna', '+1200', 'N', 'WFT'),
(394, 'Asia/Aden', 'Yemen', '+0300', 'N', 'AST'),
(395, 'Africa/Lusaka', 'Zambia', '+0200', 'N', 'CAT'),
(396, 'Africa/Harare', 'Zimbabwe', '+0200', 'N', 'CAT');

INSERT INTO `role` (`id`, `name`, `description`) VALUES(1, 'login', 'Login privileges, granted after account confirmation');
INSERT INTO `role` (`id`, `name`, `description`) VALUES(2, 'admin', 'Administrative user, has access to everything.');
INSERT INTO `role` (`id`, `name`, `description`) VALUES(3, 'superadmin', 'Super admin, role for root user');

-- root@localhost.com with 123456
INSERT INTO `user` (`id`, `email`, `password`) VALUES (2, 'root@localhost.com', 'ddcc15b8f30f3903f57ced5a9085cad4ec6fd564ec5125abd8c943bcb3e8f8ef');

INSERT INTO `role_user` (`user_id`, `role_id`) VALUES
(2, 1),
(2, 2),
(2, 3);

INSERT INTO `page` (`id`, `title`, `slug`, `text`, `is_hidden`) VALUES (NULL, 'Описание', 'description', NULL, '1');
INSERT INTO `page` (`id`, `title`, `slug`, `text`, `is_hidden`) VALUES (NULL, 'Частые вопросы', 'faq', NULL, '0');
INSERT INTO `page` (`id`, `title`, `slug`, `text`, `is_hidden`) VALUES (NULL, 'Контакты', 'contacts', NULL, '0');
INSERT INTO `page` (`id`, `title`, `slug`, `text`, `is_hidden`) VALUES (NULL, 'Полезная информация', 'info', NULL, '0');
INSERT INTO `page` (`id`, `title`, `slug`, `text`, `is_hidden`) VALUES (NULL, 'Условия использования', 'agreement', NULL, '1');

-- System templates
INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('user_template_1', '1', 2, 'Поздравляю Вас с Днем вашей свадьбы!', 'Поздравляю Вас с Днем вашей свадьбы!', 'Уважаемые %ИМЯ% и %ИМЯ РОДСТВЕННИКА%!
Я искренне поздравляю Вас с днем Вашей свадьбы.
Вы – прекрасная пара, и мне доставило огромное удовольствие работать с Вами.
Я желаю Вам многих лет крепкой любви, дружбы и взаимных радостей.

С уважением,
%МОЕ ИМЯ% %МОЯ ФАМИЛИЯ%');

INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('user_template_2', '1', 2, 'С Днем Рождения, %ИМЯ%', 'С Днем Рождения, %ИМЯ%', '%ИМЯ%!
Я поздравляю тебя с Днем твоего Рождения!
Желаю тебе крепкого здоровья и быстрого и эффективного достижения поставленных целей!

%МОЕ ИМЯ%');
INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('signup_email_confirm', '1', 2, 'Регистрация на сайте %НАЗВАНИЕ САЙТА%', 'Регистрация на сайте %НАЗВАНИЕ САЙТА%', 'Для завершения регистрации, перейдите, пожалуйста, по ссылке:

%ССЫЛКА%');
INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('password_reset_ask', '1', 2, 'Сброс пароля на сайте %НАЗВАНИЕ САЙТА%', 'Сброс пароля на сайте %НАЗВАНИЕ САЙТА%', 'Чтобы сбросить пароль, перейдите, пожалуйста, по ссылке:

%ССЫЛКА%');
INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('affiliate_invite', '1', 2, 'Посмотри, это полезная штука для автоматических поздравлений твоих клиентов', 'Посмотри, это полезная штука для автоматических поздравлений твоих клиентов', 'Привет! Посмотри на этот сервис – очень полезен для позравлений твои клиентов автоматически. Регистрируйся по ссылке:

%ССЫЛКА%

%МОЕ ИМЯ% <%МОЙ E-MAIL%>');


INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('mailing_upcoming_messages', '1', 2, 'План поздравлений на 10 дней', 'План поздравлений на 10 дней', '<p>Здравствуйте, %МОЕ ИМЯ%.</p>

<p>Вас беспокоит администрация %НАЗВАНИЕ САЙТА%</p>
<p>На ближайшие 10 дней у Вас запланированы следующие поздравления. Если вдруг Вы хотите купить подарок или поздравить кого-то из списка лично, то включите это в Ваш список запланированных дел.</p>

%РАСПИСАНИЕ%

<address>С уважением,<br/>
Администрация %НАЗВАНИЕ САЙТА%</address>
');

INSERT INTO `mail_template` (`code`, `system`, `user_id`, `name`, `subject`, `body`) VALUES('alert_balance', '1', 2, 'У вас осталось L поздравлений', 'У вас осталось %КОЛИЧЕСТВО% поздравлений', '<p>Позовите друзей и коллег, чтобы увеличить кол-во доступных писем.</p> 

<p>Ваша партнерская ссылка: %ССЫЛКА%.</p> 
<p>%ПАРТНЕРСКАЯ ПРОГРАММА РАЗДЕЛ ССЫЛКА%</p>

<address>С уважением,<br/>
Администрация %НАЗВАНИЕ САЙТА%</address>
');
